// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "get",
  path: "/logout",
  handler: function(req, h) {
    req.cookieAuth.clear();
    return {
      valid: true,
      msg: "登出成功"
    };
  }
};
