// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "get",
  path: "/api/auth/valid",
  handler: function(req, h) {
    var auth;
    auth = req.auth.credentials;
    return {
      valid: true,
      msg: "验证成功",
      data: auth.icat_users_extend
    };
  }
};
