// Generated by CoffeeScript 2.6.1
var fs, pathLib;

pathLib = require("path");

fs = require("fs-extra");

module.exports = async function(uid) {
  var err, tmp, userDir;
  try {
    userDir = pathLib.resolve("./www/data/" + (tmp = 10 ** 10 + uid * 1 + "").slice(1, tmp.length).match(/../g).join("/"));
    return (await fs.mkdirs(userDir));
  } catch (error) {
    err = error;
    return console.log(err);
  }
};
