// Generated by CoffeeScript 2.6.1
var Op, db, fn;

db = require("./db_main");

({Op} = require("sequelize"));

// 更新统计
fn = async function() {
  var err, i, item, len, ref, ref1, t, users;
  t = (await db.mysql.transaction());
  try {
    users = (await db.icat_users.findAll({
      attributes: ["uid"]
    }));
    for (i = 0, len = users.length; i < len; i++) {
      item = users[i];
      await db.icat_users_extend.update({
        postCount: (await db.icat_posts.count({
          where: {
            uid: item.uid,
            linkid: 0
          },
          transaction: t
        })),
        replyCount: (await db.icat_posts.count({
          where: {
            uid: item.uid,
            linkid: {
              [Op.ne]: 0
            }
          },
          transaction: t
        })),
        likeCount: (Object.keys(JSON.parse((ref = (ref1 = (await db.icat_posts.findOne({
          attributes: ["likes"],
          where: {
            uid: item.uid
          }
        }))) != null ? ref1.likes : void 0) != null ? ref : "{}"))).length,
        transaction: t,
        friendCount: 0
      }, {
        where: {
          uid: item.uid
        }
      }, {
        transaction: t
      });
    }
    await t.commit();
    return console.log("已同步数据");
  } catch (error) {
    err = error;
    t.rollback();
    return console.log(err);
  }
};

setInterval(fn, 5 * 60 * 1000);

module.exports = fn;
