// Generated by CoffeeScript 2.6.1
/*
  desc
  linkid
  limit
*/
module.exports = {
  method: "get",
  path: "/api/posts/get",
  options: {
    auth: false
  },
  handler: async function(req, h) {
    var auth, db, err, que, tmp;
    try {
      db = req.server.db;
      que = req.query;
      auth = req.auth.credentials;
      if (que.pid) { //如果提供pid，说明需要返回单个帖子
        tmp = (await db.icat_posts.findByPk(que.pid, {
          include: db.icat_users_extend // 否则使用linkid查询帖子列表
        }));
      } else {
        tmp = (await db.icat_posts.findAll({
          include: db.icat_users_extend,
          where: {
            linkid: que.linkid ? que.linkid * 1 : 0
          },
          order: [["isTop", "DESC"], ["pid", que.desc ? "desc" : "ASC"]],
          limit: que.limit ? que.limit * 1 : 999999
        }));
      }
      return {
        valid: true,
        msg: "操作成功",
        data: tmp,
        allCount: (await db.icat_posts.count({
          where: {
            linkid: que.linkid ? que.linkid * 1 : 0
          }
        }))
      };
    } catch (error) {
      err = error;
      console.log(err);
      return {
        valid: false,
        msg: "服务器内部错误"
      };
    }
  }
};
