// Generated by CoffeeScript 2.6.1
/*
pid
*/
module.exports = {
  method: "post",
  path: "/api/posts/like",
  handler: async function(req, h) {
    var auth, db, err, que, tmp;
    try {
      db = req.server.db;
      que = req.payload;
      auth = req.auth.credentials;
      await db.icat_posts.update({
        likes: (tmp = ((await db.icat_posts.findOne({
          where: {
            pid: que.pid
          }
        }))).likes) ? (tmp = JSON.parse(tmp))[auth.uid] ? (delete tmp[auth.uid], JSON.stringify(tmp)) : (tmp[auth.uid] = auth.user, JSON.stringify(tmp)) : (tmp = {}, tmp[auth.uid] = auth.user, JSON.stringify(tmp))
      }, {
        where: {
          pid: que.pid
        }
      });
      return {
        valid: true,
        msg: "赞操作成功"
      };
    } catch (error) {
      err = error;
      console.log(err);
      return {
        valid: false,
        msg: "服务器内部错误"
      };
    }
  }
};
