// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "post",
  path: "/api/posts/del",
  handler: async function(req, h) {
    var auth, db, e, fn, isMine, que, t;
    que = req.payload;
    auth = req.auth.credentials;
    db = req.server.db;
    t = (await db.mysql.transaction());
    try {
      fn = async function(pid) {
        var i, item, len, tmp;
        tmp = (await db.icat_posts.findAll({
          where: {
            linkid: que.pid
          }
        }, {
          transaction: t
        }));
        for (i = 0, len = tmp.length; i < len; i++) {
          item = tmp[i];
          if (!tmp[0]) {
            await fn(tmp.pid);
          }
        }
        await db.icat_posts.destroy({
          where: {
            pid: pid
          }
        }, {
          transaction: t
        });
        return (await t.commit());
      };
      isMine = (await db.icat_posts.findOne({
        where: {
          pid: que.pid,
          author: auth.user
        },
        transaction: t
      }));
      if (isMine || auth.icat_users_extend.power > 90) {
        await fn(que.pid);
        return {
          valid: true,
          msg: "删除成功"
        };
      } else {
        return {
          valid: false,
          msg: "权限不足"
        };
      }
    } catch (error) {
      e = error;
      await t.rollback();
      return console.log(e);
    }
  }
};
