// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "get",
  path: "/api/notice/getNew",
  handler: function(req, h) {
    var auth, db, err, que;
    que = req.query;
    db = req.server.db;
    auth = req.auth.credentials;
    try {

    } catch (error) {
      err = error;
      console.log(err);
      return {
        valid: false,
        msg: "服务器内部错误"
      };
    }
  }
};
