// Generated by CoffeeScript 2.6.1
/*
  @key que.key
  @value que.value
*/
module.exports = {
  method: "post",
  path: "/api/vars/get",
  handler: async function(req, h) {
    var auth, data, db, err, que, ref;
    que = req.payload;
    db = req.server.db;
    auth = req.auth.credentials;
    try {
      data = (await db.icat_vars.findOne({
        where: {
          uid: auth.uid,
          key: que.key
        }
      }));
      return {
        valid: true,
        data: (ref = data != null ? data.value : void 0) != null ? ref : void 0
      };
    } catch (error) {
      err = error;
      console.log(err);
      return {
        valid: false,
        msg: "服务器内部错误"
      };
    }
  }
};
