// Generated by CoffeeScript 2.6.1
/*
  @key que.key
  @value que.value
*/
module.exports = {
  method: "post",
  path: "/api/vars/getMany",
  handler: async function(req, h) {
    var auth, data, db, err, que;
    que = req.payload;
    db = req.server.db;
    auth = req.auth.credentials;
    try {
      data = (await db.icat_vars.findAll());
      return {
        valid: true,
        data: data != null ? data : void 0
      };
    } catch (error) {
      err = error;
      console.log(err);
      return {
        valid: false,
        msg: "服务器内部错误"
      };
    }
  }
};
